server:
  port: 8080

spring:
  application:
    name: bic-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/bic_cecam
    username: bic_user
    password: admin123
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false